name: Development Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: Run ESLint
        run: npm run lint -- --format=json --output-file=eslint-report.json || true

      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: eslint-report
          path: eslint-report.json

      - name: Check TypeScript compilation
        run: npx tsc --noEmit

      - name: Check bundle size
        run: |
          npm run build
          du -sh dist/

      - name: Comment PR with bundle size
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');

            try {
              const bundleSize = execSync('du -sh dist/ | cut -f1').toString().trim();
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `📦 Bundle size: **${bundleSize}**`
              });
            } catch (error) {
              console.log('Could not determine bundle size:', error.message);
            }
